spring.datasource.url=jdbc:mysql://localhost:3306/ORDER_MGMT?useSSL=false
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# App Properties
security.jwt.secret-key= ======================Kartik===========================
security.jwt.expiration-time=86400000